// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package awsClient

import (
	"github.com/aws/aws-sdk-go-v2/service/rds"
)

// Injectors from container.go:

func NewRDSSnapshotService() *RDSSnapshotService {
	client := NewRDSClient()
	rdsSnapshotService := GetNewRDSSnapshotService(client)
	return rdsSnapshotService
}

// container.go:

func NewRDSClient() *rds.Client {
	return rds.NewFromConfig(NewConfig())
}
